-- MySQL Script generated by MySQL Workbench
-- Thu May  2 14:56:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2024mca_auto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2024mca_auto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2024mca_auto` DEFAULT CHARACTER SET utf8 ;
USE `2024mca_auto` ;

-- -----------------------------------------------------
-- Table `2024mca_auto`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Admin` TINYINT NULL DEFAULT 0,
  `Blocked` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024mca_auto`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`Brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024mca_auto`.`EngineTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`EngineTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Type_UNIQUE` (`Type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024mca_auto`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NOT NULL,
  `Year` SMALLINT UNSIGNED NOT NULL,
  `mileage` MEDIUMINT UNSIGNED NOT NULL,
  `Images` VARCHAR(255) NOT NULL,
  `Description` LONGTEXT NULL,
  `brand_id` INT NOT NULL,
  `engineType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cars_Brands1_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_Cars_EngineTypes1_idx` (`engineType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `2024mca_auto`.`Brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_EngineTypes1`
    FOREIGN KEY (`engineType_id`)
    REFERENCES `2024mca_auto`.`EngineTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024mca_auto`.`Notices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`Notices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PublicationDate` DATE NOT NULL,
  `BuyDate` DATE NULL,
  `Price` INT UNSIGNED NOT NULL,
  `Active` TINYINT NULL DEFAULT 1,
  `Blocked` TINYINT NULL DEFAULT 0,
  `buyer_id` INT NULL,
  `seller_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notices_Users2_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_Notices_Users1_idx` (`seller_id` ASC) VISIBLE,
  INDEX `fk_Notices_Cars1_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notices_Users2`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `2024mca_auto`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notices_Users1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `2024mca_auto`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notices_Cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `2024mca_auto`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2024mca_auto`.`Users_Bookmark_Notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2024mca_auto`.`Users_Bookmark_Notice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `notice_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_Notice_Notice1_idx` (`notice_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Notice_Users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `notice_id_UNIQUE` (`notice_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Notice_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `2024mca_auto`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Notice_Notice1`
    FOREIGN KEY (`notice_id`)
    REFERENCES `2024mca_auto`.`Notices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
